name: Verify
on: [push, pull_request]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: bundle exec rspec
